# Generated by Django 4.2.28 on 2026-03-04 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_orderitem_status_orderitem_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='currency',
            field=models.CharField(default='XAF', max_length=3),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='marketplace.order'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payer_msisdn',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='raw_request',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
